-- query against the SH schema generated by swingbench
SELECT  /*+ monitor */ sum(B.AMOUNT_SOLD) amt_sold,
  A.PROD_CATEGORY
FROM SALES B,
  PRODUCTS A
WHERE A.PROD_ID = B.PROD_ID 
and A.PROD_CATEGORY = 'Hardware'
group by A.PROD_CATEGORY;